/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

type Language = 'ar' | 'en';

const translationData = {
    ar: {
        title: 'رحلة عبر الزمن',
        subtitle: 'شاهد نفسك عبر العقود.',
        uploadInstructions: 'انقر على الصورة لتحميل صورتك وبدء رحلتك عبر الزمن.',
        freeMessage: 'مجاني تمامًا. لا يتطلب تسجيل. بدون فترة تجريبية.',
        templatesTitle: 'أو اختر شخصية جاهزة',
        filterTitle: 'اختر فلترًا',
        generatePrompt: (decade: string) => `أعد تصور الشخص في هذه الصورة بأسلوب عقد ${decade}. يجب أن يشمل هذا الملابس، تسريحة الشعر، جودة الصورة، والجمالية العامة لذلك العقد. يجب أن يكون الناتج صورة واقعية تظهر الشخص بوضوح.`,
        buttons: {
            differentPhoto: 'صورة مختلفة',
            generate: 'إنشاء',
            shareResults: 'مشاركة النتائج',
            readyPrompts: 'مطالبات جاهزة',
            downloadAlbum: 'تحميل الألبوم',
            creatingAlbum: 'جاري إنشاء الألبوم...',
            startOver: 'البدء من جديد',
        },
        polaroid: {
            clickToStart: 'انقر للبدء',
            yourPhoto: 'صورتك',
            uploadPlaceholder: 'تحميل صورة',
        },
        filters: {
            noFilter: 'بدون فلتر',
            sepia: 'سيبيا',
            bw: 'أبيض وأسود',
            vintage: 'فينتاج',
        },
        alerts: {
            filterError: 'لا يمكن تطبيق الفلتر المحدد. سيتم المتابعة بالصورة الأصلية.',
            waitAllImages: 'يرجى الانتظار حتى تنتهي جميع الصور من التحميل قبل تنزيل الألبوم.',
            albumError: 'عذرًا، حدث خطأ أثناء إنشاء ألبومك. يرجى المحاولة مرة أخرى.',
        },
        promptModal: {
            title: 'مطالبات جاهزة للإلهام',
            closeAriaLabel: 'إغلاق',
            copy: 'نسخ',
            copied: 'تم النسخ!',
            copyAriaLabel: 'نسخ المطالبة',
        },
        footer: {
            developedBy: 'تم التطوير بواسطة',
        },
        share: {
            title: 'رحلة عبر الزمن بالذكاء الاصطناعي',
            text: 'لقد سافرت عبر الزمن! شاهد صوري من عقود مختلفة تم إنشاؤها بواسطة الذكاء الاصطناعي.',
            alert: 'تم نسخ الرابط! شاركه مع أصدقائك.',
        },
        album: {
            header: 'تم إنشاؤه بواسطة رحلة عبر الزمن',
            subheader: 'على Google AI Studio',
        },
    },
    en: {
        title: 'Past Forward',
        subtitle: 'See yourself through the decades.',
        uploadInstructions: 'Click the polaroid to upload your photo and begin your time travel.',
        freeMessage: 'Completely free. No registration required. No trial period.',
        templatesTitle: 'Or choose a ready character',
        filterTitle: 'Choose a Filter',
        generatePrompt: (decade: string) => `Reimagine the person in this photo in the style of the ${decade}. This includes clothing, hairstyle, photo quality, and the overall aesthetic of that decade. The output must be a photorealistic image showing the person clearly.`,
        buttons: {
            differentPhoto: 'Different Photo',
            generate: 'Generate',
            shareResults: 'Share Results',
            readyPrompts: 'Ready Prompts',
            downloadAlbum: 'Download Album',
            creatingAlbum: 'Creating Album...',
            startOver: 'Start Over',
        },
        polaroid: {
            clickToStart: 'Click to Start',
            yourPhoto: 'Your Photo',
            uploadPlaceholder: 'Upload Photo',
        },
        filters: {
            noFilter: 'No Filter',
            sepia: 'Sepia',
            bw: 'B & W',
            vintage: 'Vintage',
        },
        alerts: {
            filterError: 'Could not apply the selected filter. Proceeding with the original image.',
            waitAllImages: 'Please wait for all images to finish generating before downloading the album.',
            albumError: 'Sorry, there was an error creating your album. Please try again.',
        },
        promptModal: {
            title: 'Ready Prompts for Inspiration',
            closeAriaLabel: 'Close',
            copy: 'Copy',
            copied: 'Copied!',
            copyAriaLabel: 'Copy prompt',
        },
        footer: {
            developedBy: 'Developed by',
        },
        share: {
            title: 'AI Time Travel',
            text: 'I traveled through time! Check out my photos from different decades generated by AI.',
            alert: 'Link copied! Share it with your friends.',
        },
        album: {
            header: 'Created with Past Forward',
            subheader: 'on Google AI Studio',
        },
    }
};

const promptsData = {
    ar: [
        { title: 'فني', prompt: 'حوّل الشخص في هذه الصورة إلى لوحة زيتية كلاسيكية، مع التركيز على القوام الغني والظلال العميقة والإضاءة الدرامية بأسلوب فنان أوروبي قديم.' },
        { title: 'بطل خارق', prompt: 'أعد تصور الشخص كبطل خارق، وامنحه زيًا فريدًا ومفصلاً يعكس قواه. يجب أن تكون الخلفية مشهد مدينة ديناميكي عند الغسق.' },
        { title: 'خيال علمي', prompt: 'ضع الشخص في مدينة سيبرانية مستقبلية. يجب أن تكون الصورة مليئة بأضواء النيون والهياكل المعمارية المستقبلية والتكنولوجيا المتقدمة.' },
        { title: 'فن البكسل', prompt: 'حوّل الصورة إلى عمل فني بكسل مفصل بأسلوب 16 بت، مشابه لألعاب الفيديو الكلاسيكية من حقبة التسعينيات.' },
        { title: 'أنمي', prompt: 'أعد رسم الشخص كشخصية رئيسية في فيلم أنمي، بأسلوب فني مستوحى من استوديو جيبلي، مع خلفية طبيعية خلابة.' },
        { title: 'ستيم بانك', prompt: 'أعد تصور الشخص بجمالية ستيم بانك متقنة. قم بتضمين ملابس من العصر الفيكتوري مع تروس نحاسية ونظارات واقية وأدوات ميكانيكية معقدة.' }
    ],
    en: [
        { title: 'Artistic', prompt: 'Transform the person in this photo into a classical oil painting, capturing the rich textures, deep shadows, and dramatic lighting of a European master\'s style.' },
        { title: 'Superhero', prompt: 'Reimagine the person as a superhero, giving them a unique and detailed costume that reflects their powers. The background should be a dynamic city scene at dusk.' },
        { title: 'Sci-Fi', prompt: 'Place the person into a futuristic, cyberpunk cityscape. The image should be filled with neon lights, futuristic architecture, and advanced technology.' },
        { title: 'Pixel Art', prompt: 'Convert the photo into a detailed 16-bit pixel art piece, reminiscent of classic video games from the SNES era.' },
        { title: 'Anime', prompt: 'Redraw the person as a main character in an anime film, with an art style inspired by Studio Ghibli, set against a beautiful natural backdrop.' },
        { title: 'Steampunk', prompt: 'Reimagine the person with an elaborate steampunk aesthetic. Include Victorian-era clothing mixed with brass gears, goggles, and intricate mechanical gadgets.' }
    ]
};

const templatesData = {
    ar: [
        { name: 'رجل 1', url: 'https://i.ibb.co/6nB1f8d/pexels-photo-220455.jpg' },
        { name: 'امرأة 1', url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
        { name: 'رجل 2', url: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
        { name: 'امرأة 2', url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
    ],
    en: [
        { name: 'Man 1', url: 'https://i.ibb.co/6nB1f8d/pexels-photo-220455.jpg' },
        { name: 'Woman 1', url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
        { name: 'Man 2', url: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
        { name: 'Woman 2', url: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
    ]
};

export const translations = translationData;
export const getPrompts = (lang: Language) => promptsData[lang];
export const getTemplates = (lang: Language) => templatesData[lang];